.TH DH_PYTHON3 "1" "September 2010" "dh_python3 3.0~beta2" "User Commands"
.SH NAME
dh_python3 \- calculates Python 3 dependencies, adds maintainer scripts to byte compile files, etc.
.SH SYNOPSIS
.B dh_python3
\fI-p PACKAGE \fR[\fI-V \fR[\fIX.Y\fR][\fI-\fR][\fIA.B\fR]] \fIDIR_OR_FILE \fR[\fI-X REGEXPR\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-no\-guessing\-deps\fR
disable guessing dependencies
.TP
\fB\-\-no\-dbg\-cleaning\fR
do not remove any files from debug packages
.TP
\fB\-\-skip\-private\fR
don't check private directories
.TP
\fB\-v\fR, \fB\-\-verbose\fR
turn verbose mode on
.TP
\fB\-i\fR, \fB\-\-indep\fR
act on architecture independent packages
.TP
\fB\-a\fR, \fB\-\-arch\fR
act on architecture dependent packages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
be quiet
.TP
\fB\-p\fR PACKAGE, \fB\-\-package\fR=\fIPACKAGE\fR
act on the package named PACKAGE
.TP
\fB\-N\fR NO_PACKAGE, \fB\-\-no\-package\fR=\fINO_PACKAGE\fR
do not act on the specified package
.TP
\fB\-V\fR VRANGE
specify list of supported Python versions. See
py3compile(1) for examples
.TP
\fB\-X\fR REGEXPR, \fB\-\-exclude\fR=\fIREGEXPR\fR
exclude items that match given REGEXPR. You may use
this option multiple times to build up a list of
things to exclude.
.TP
.B \-\-compile\-all
compile all files from given private directory in postinst/rtupdate
not just the ones provided by the package (i.e. do not pass the \-\-package
parameter to py3compile/py3clean)
.TP
\fB\-\-depends\fR=\fIDEPENDS\fR
translate given requirements into Debian dependencies
and add them to ${python:Depends}. Use it for missing
items in requires.txt.
.TP
\fB\-\-recommends\fR=\fIRECOMMENDS\fR
translate given requirements into Debian dependencies
and add them to ${python:Recommends}
.TP
\fB\-\-suggests\fR=\fISUGGESTS\fR
translate given requirements into Debian dependencies
and add them to ${python:Suggests}
.SH "SEE ALSO"
/usr/share/doc/python3-doc/README.PyDist (python3-doc package)
