#! /usr/bin/python3
# vim: et ts=4 sw=4

# Copyright © 2010 Piotr Ożarowski <piotr@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import logging
import optparse
import sys
from glob import glob1
from os import environ, remove, rmdir, walk
from os.path import dirname, exists, isdir, isfile, join
from subprocess import Popen, PIPE
sys.path.insert(1, '/usr/share/python3/')
from debpython.version import SUPPORTED, getver, vrepr


# initialize script
logging.basicConfig(format='%(levelname).1s: %(module)s:%(lineno)d: '
                           '%(message)s')
log = logging.getLogger(__name__)

"""TODO: move it to manpage
Examples:
    py3clean -p python3-mako # all .py[co] files and __pycache__ directories from the package
    py3clean /usr/lib/python3.1/dist-packages # python3.1
    py3clean -V 3.3 /usr/lib/python3/ # python 3.3 only
    py3clean -V 3.3 /usr/lib/foo/bar.py # bar/__pycache__/bar.cpython-33.py[co]
    py3clean /usr/lib/python3/ # all Python 3.X
"""


def get_magic_tags_map(version=None):
    """Return Python magic tags for installed Python versions."""

    to_check = set(SUPPORTED) - {(3, 1)}
    if version and version != (3, 1):
        to_check.add(version)
    cmd = ''
    for v in ('.'.join(str(j) for j in i) for i in to_check):
        if not exists("/usr/bin/python%s" % v):
            log.debug("version %s not installed, skipping", v)
            continue

        cmd += "/usr/bin/python%s -c 'import imp; print(\"%s_\"" % (v, v) + \
               "+imp.get_tag())' && "

    result = {}
    if not cmd:
        return result
    cmd = cmd[:-3]  # cut last '&& '
    log.debug("invoking %s", cmd)
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
    if p.wait() != 0:
        log.debug(p.stderr.read())
        log.error('cannot get magic tags')
        exit(3)
    else:
        for line in p.stdout:
            version, magic_tag = str(line, 'utf-8').split('_', 2)
            version = getver(version)
            # Python 3.X returns bytes
            magic_tag = magic_tag.strip().lstrip("b'").rstrip("'")
            result.setdefault(version, set()).add(magic_tag)
    log.debug('magic tags map: %s', result)
    return result


def get_magic_tags_to_remove(version):
    """Returns set of numbers or True if all of them should be removed."""
    map_ = get_magic_tags_map(version)
    if version != (3, 1) and version not in map_:
        log.error('magic tag for %s not recognized', vrepr(version))
        exit(4)

    result = set(map_[version])  # make a copy
    for v, numbers in map_.items():
        if v == version:
            continue
        result = result.difference(numbers)

    if not result:
        log.info('magic tag(s) used by another installed\
Python version. Nothing to remove.')
        exit(0)

    log.debug('magic tags to remove: %s', result)
    return result


def destroyer(magic_tags=None):  # ;-)
    """Remove every .py[co] file associated to received .py file.

    :param magic_tags: if None, removes __pycache__ directories,
        if False, removes python3.1's .pyc files only,
        otherwise removes set of magic tags from __pycache__ directory
    :type magic_tags: None or False or set"""
    if magic_tags is None:

        # remove all files in __pycache__ directory
        def find_files_to_remove(pyfile):
            directory = "%s/__pycache__/" % dirname(pyfile)
            for fn in glob1(directory, '*'):
                yield join(directory, fn)
            # remove "classic" .pyc files as well
            for filename in ("%sc" % pyfile, "%so" % pyfile):
                if exists(filename):
                    yield filename
    elif magic_tags is False:

        # remove 3.1's .pyc files only
        def find_files_to_remove(pyfile):
            for filename in ("%sc" % pyfile, "%so" % pyfile):
                if exists(filename):
                    yield filename
    else:

        # remove .pyc files for no longer needed magic tags
        def find_files_to_remove(pyfile):
            directory = "%s/__pycache__/" % dirname(pyfile)
            for i in magic_tags:
                for fn in glob1(directory, "*.%s.py[co]" % i):
                    yield join(directory, fn)

    def myremove(fname):
        remove(fname)
        directory = dirname(fname)
        # remove __pycache__ directory if it's empty
        if directory.endswith('__pycache__'):
            try:
                rmdir(directory)
            except:
                pass

    counter = 0
    try:
        while True:
            pyfile = (yield)
            for filename in find_files_to_remove(pyfile):
                try:
                    myremove(filename)
                    counter += 1
                except (IOError, OSError) as e:
                    log.error('cannot remove %s', filename)
                    log.debug(e)
    except GeneratorExit:
        log.info("removed files: %s", counter)


def get_files(items):
    for item in items:
        if isfile(item) and item.endswith('.py'):
            yield item
        elif isdir(item):
            for root, dirs, files in walk(item):
                #for fn in glob1(root, '*.py'):
                #    yield join(root, fn)
                for fn in files:
                    if fn.endswith('.py'):
                        yield join(root, fn)


def get_package_files(package_name):
    process = Popen("/usr/bin/dpkg -L %s" % package_name,\
                    shell=True, stdout=PIPE)
    stdout, stderr = process.communicate()
    if process.returncode != 0:
        log.error('cannot get content of %s', package_name)
        exit(2)
    stdout = str(stdout, 'utf-8')
    for line in stdout.split('\n'):
        if line.endswith('.py'):
            yield line


def main():
    usage = '%prog [-V VERSION] [-p PACKAGE | DIR_OR_FILE]'
    parser = optparse.OptionParser(usage, version='%prog 0.3')
    parser.add_option('-v', '--verbose', action='store_true', dest='verbose',
        help='turn verbose more one')
    parser.add_option('-q', '--quiet', action='store_false', dest='verbose',
        default=False, help='be quiet')
    parser.add_option('-p', '--package',
        help='specify Debian package name to clean')
    parser.add_option('-V', dest='version',
        help='specify Python version to clean')

    (options, args) = parser.parse_args()

    if options.verbose or environ.get('PYCLEAN_DEBUG') == '1':
        log.setLevel(logging.DEBUG)
        log.debug('argv: %s', sys.argv)
        log.debug('options: %s', options)
        log.debug('args: %s', args)
    else:
        log.setLevel(logging.WARNING)

    if options.version:
        if options.version.endswith('3.1'):  # 3.1, -3.1
            magic_tags = False
        else:
            magic_tags = get_magic_tags_to_remove(getver(options.version))
        d = destroyer(magic_tags)
    else:
        d = destroyer()  # remove everything
    next(d)  # initialize coroutine

    if options.package and args:
        parser.error('only one action is allowed at the same time ('
                     'cleaning directory or a package)')

    if options.package:
        log.info('cleaning package %s', options.package)
        for filename in get_package_files(options.package):
            d.send(filename)
    elif args:
        log.info('cleaning directories: %s', args)
        for filename in get_files(args):
            d.send(filename)
    else:
        parser.print_usage()
        exit(1)

if __name__ == '__main__':
    main()
